const menuData = [
  {
    id: 1,
    title: "albarino",
    category: "drinks",
    price: 12,
    desc: `crisp, light body, floral`,
  },
  {
    id: 2,
    title: "chardonnay",
    category: "drinks",
    price: 14,
    desc: `buttery, medium body, nutty`,
  },
  {
    id: 3,
    title: "beaujoleais",
    category: "drinks",
    price: 15,
    desc: `ripe cherry, medium body, slightly earthy`,
  },
  {
    id: 4,
    title: "cabernet blend",
    category: "drinks",
    price: 17,
    desc: `dark berries, full body, fruit forward`,
  },
  {
    id: 5,
    title: "lager beer",
    category: "drinks",
    price: 6,
    desc: `rotating selection`,
  },
  {
    id: 6,
    title: "sake",
    category: "drinks",
    price: 12,
    desc: `rotating selection`,
  },
  {
    id: 7,
    title: "seaweed salad",
    category: "appetizers",
    price: 6,
    desc: `soy sauce, mirin, sesame`,
  },
  {
    id: 8,
    title: "tuna tataki",
    category: "appetizers",
    price: 16,
    desc: `yuzu, ginger, agave-soy sauce`,
  },
  {
    id: 9,
    title: "yellowtail sashimi",
    category: "appetizers",
    price: 19,
    desc: `serrano pepper, cilantro`,
  },
  {
    id: 10,
    title: "octopus ceviche",
    category: "appetizers",
    price: 19,
    desc: `sea salt, yuzu`,
  },
  {
    id: 11,
    title: "stuffed tomato",
    category: "appetizers",
    price: 14,
    desc: `crab, shrip, salmon`,
  },
  {
    id: 12,
    title: "cherry blossom",
    category: "appetizers",
    price: 12,
    desc: `crab, avocado, unagi sauce`,
  },
  {
    id: 13,
    title: "black cod",
    category: "entrees",
    price: 21,
    desc: `miso marinate, black rice, seasonal veggies`,
  },
  {
    id: 14,
    title: "tonkatsu ramen",
    category: "entrees",
    price: 15,
    desc: `breaded pork cutlets, spicy miso, nori`,
  },
  {
    id: 15,
    title: "teriyaki filet",
    category: "entrees",
    price: 24,
    desc: `beef filet, carrot, yuzu-ginger relish`,
  },
  {
    id: 16,
    title: "teriyaki chicken",
    category: "entrees",
    price: 15,
    desc: `marinated chicken, soba noodle, watermelon radish`,
  },
  {
    id: 17,
    title: "to-ban yaki",
    category: "entrees",
    price: 24,
    desc: `marinated pork, mushroom, asparagus`,
  },
  {
    id: 18,
    title: "steamed mussels",
    category: "entrees",
    price: 20,
    desc: `compound butter, sake sauce, tempura fries`,
  },
  {
    id: 19,
    title: "dark chocolate mochi",
    category: "desserts",
    price: 6,
    desc: `3 pieces`,
  },
  {
    id: 20,
    title: "macha crepe cake",
    category: "desserts",
    price: 11,
    desc: `white chocolate buttercream, strawberries`,
  },
  {
    id: 21,
    title: "black sesame cake",
    category: "desserts",
    price: 11,
    desc: `dark chocolate, vanilla ice cream`,
  },
  {
    id: 22,
    title: "yuzu tart",
    category: "desserts",
    price: 11,
    desc: `almond crust, miso whipped cream`,
  },
];

export default menuData;
